<?php

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Framework\View\Element\Template $block
 */

$productPrice = $this->helper(\Magento\Catalog\Helper\Data::class)->getProduct()->getFinalPrice();
$helper = $this->helper(\Dorn\Loyalty\Helper\Data::class);
$shouldDisplayMessage = $helper->shouldDisplayCoinsBackMessage();
$mightBeReceivedCoins = $helper->calculateCoinsBackAmount($productPrice);

if ($shouldDisplayMessage) {
    echo '<div>' . __('You will receive %1 coins for purchasing this product.', $mightBeReceivedCoins) . '</div>';
}

?>

<div>
    <?= $block->getChildHtml('test.block') ?>
</div>
